### ISSUE TITLE
🚀 Feature: Adding Seven, Sinch, Infobip, Clickatell and Plivo SMS adapters

### ISSUE THREAD

**Issue by byawitz** [utopia-php/messaging#17]
### 🔖 Feature description

Adding adapter for the following SMS providers
- [X] Seven
- [X] Sinch
- [X] Infobip
- [X] Clickatell 
- [X] Plivo

Also, having a quick pricing overview from low to high for a specific country would be good because there are so many SMS providers.

I've added those I'm using; of course, more can be added the same way.

### 🎤 Pitch

Different Adapters have much lower prices in certain situations. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/utopia-php/messaging/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by byawitz** [comment]
And I missed the rule to create an Issue and then the PR.
So this is the issue, and this is the PR
https://github.com/utopia-php/messaging/pull/16

**Comment by abnegate** [comment]
Closing as completed, thanks for your patience and hard work @byawitz
