### ISSUE TITLE
Doesn't match MSG91 API (does it even work?)

### ISSUE THREAD

**Issue by Megamannen** [utopia-php/messaging#23]
The API wants these values (https://api.msg91.com/api/v5/flow/)
```json
{ 
"template_id":"EntertemplateID", 
"short_url": "1 (On) or 0 (Off)",   
 "recipients" : [     {       "mobiles":"919XXXXXXXXX",       "VAR1": "VALUE1",       "VAR2": "VALUE2"         }   ] }
```

Not even close to what is actually sent
https://github.com/utopia-php/messaging/blob/2d0f474a106bb1da285f85e105c29b46085d3a43/src/Utopia/Messaging/Adapters/SMS/Msg91.php#L56

**Comment by abnegate** [comment]
@wess Please take a look here

**Comment by gaurav-chandra** [comment]
Yes, the api is not working at all and the api is changed completely [`https://docs.msg91.com/reference/sendotp`](https://docs.msg91.com/reference/sendotp)

**Comment by abhishekjain12** [comment]
`[notice] Starting worker 2fa24a0ec1ed:7:v1-messaging
[notice] Starting work on (Job{v1-messaging} | ID: a6f36964b9d36ae00016e3090331ad7a | MessagingV1 | [{"project":null,"user":null,"payload":[],"recipient":"+91123456789","message":"388486","events":["."]}])
[critical] (Job{v1-messaging} | ID: a6f36964b9d36ae00016e3090331ad7a | MessagingV1 | [{"project":null,"user":null,"payload":[],"recipient":"+91123456789","message":"388486","events":["."]}]) has failed Error: Call to a member function send() on null in /usr/src/code/app/workers/messaging.php:69
Stack trace:
#0 /usr/src/code/src/Appwrite/Resque/Worker.php(125): MessagingV1->run()
#1 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): Appwrite\Resque\Worker->perform()
#2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
#3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
#4 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
#5 {main}`

**Comment by stnguyen90** [comment]
> The API wants these values (https://api.msg91.com/api/v5/flow/)
> 
> ```json
> { 
> "template_id":"EntertemplateID", 
> "short_url": "1 (On) or 0 (Off)",   
>  "recipients" : [     {       "mobiles":"919XXXXXXXXX",       "VAR1": "VALUE1",       "VAR2": "VALUE2"         }   ] }
> ```
> 
> Not even close to what is actually sent
> 

@Megamannen Where do you see this? Looking at the [docs for the Flow API](https://api.msg91.com/apidoc/textsms/send-sms-flow.php), the parameters seem correct.

> Yes, the api is not working at all and the api is changed completely https://docs.msg91.com/reference/sendotp

@gaurav-chandra, as mentioned, Appwrite uses the [FLOW API](https://api.msg91.com/apidoc/textsms/send-sms-flow.php) and not the [Send OTP API](https://api.msg91.com/apidoc/sendotp/send-otp.php).

**Comment by stnguyen90** [comment]
> ```
> [notice] Starting work on (Job{v1-messaging} | ID: a6f36964b9d36ae00016e3090331ad7a | MessagingV1 | [{"project":null,"user":null,"payload":[],"recipient":"+91123456789","message":"388486","events":["."]}])
> [critical] (Job{v1-messaging} | ID: a6f36964b9d36ae00016e3090331ad7a | MessagingV1 | [{"project":null,"user":null,"payload":[],"recipient":"+91123456789","message":"388486","events":["."]}]) has failed Error: Call to a member function send() on null in /usr/src/code/app/workers/messaging.php:69
> Stack trace:
> #0 /usr/src/code/src/Appwrite/Resque/Worker.php(125): MessagingV1->run()
> #1 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): Appwrite\Resque\Worker->perform()
> #2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
> #3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
> #4 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
> #5 {main}```
> ```

@abhishekjain12, would you please make sure msg91 is lowercase in the `_APP_SMS_PROVIDER` env var? If you're still having troubles, please create a support post on [Discord](https://appwrite.io/discord).

**Comment by abhishekjain12** [comment]
> > ```
> > [notice] Starting work on (Job{v1-messaging} | ID: a6f36964b9d36ae00016e3090331ad7a | MessagingV1 | [{"project":null,"user":null,"payload":[],"recipient":"+91123456789","message":"388486","events":["."]}])
> > [critical] (Job{v1-messaging} | ID: a6f36964b9d36ae00016e3090331ad7a | MessagingV1 | [{"project":null,"user":null,"payload":[],"recipient":"+91123456789","message":"388486","events":["."]}]) has failed Error: Call to a member function send() on null in /usr/src/code/app/workers/messaging.php:69
> > Stack trace:
> > #0 /usr/src/code/src/Appwrite/Resque/Worker.php(125): MessagingV1->run()
> > #1 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): Appwrite\Resque\Worker->perform()
> > #2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
> > #3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
> > #4 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
> > #5 {main}```
> > ```
> 
> @abhishekjain12, would you please make sure msg91 is lowercase in the `_APP_SMS_PROVIDER` env var? If you're still having troubles, please create a support post on [Discord](https://appwrite.io/discord).

@stnguyen90  Error is gone after making `msg91`, but still the OTP hasn't been sent. I will create a Discord post.

**Comment by gaurav-chandra** [comment]
@stnguyen90 I had a talk with msg91 people and they have told me that to send OTPs, we need to use the SEND OTP API as required by the telecom authority in India. The flow is used for promotional and transactional sms only. Transactional sms take some time to arrive compared to otps. Also, the flow api used in the adapter is deprecated and will be removed in their upcoming update as they have come out with a new API for flow.

**Comment by Megamannen** [comment]
> @Megamannen Where do you see this? Looking at the [docs for the Flow API](https://api.msg91.com/apidoc/textsms/send-sms-flow.php), the parameters seem correct.

https://docs.msg91.com/reference/send-sms
![image](https://github.com/utopia-php/messaging/assets/19424456/fb035cde-9cdc-4c49-9ff0-f5389a07b9f7)
